Implement transform client-server
gabrielcalmon/apply_transform pull request #1
Opened 2023-08-02 16:44 UTC by gabrielcalmon

It was implemented a client-server solution with ros2 humble.
the src/get_transform_client.cpp defines the client, while the get_transform_server.cpp has, as its name suggests, the server.

Also, it was written a readme file with detailed usage instructions, as well as a brief documentation of the solution. 
The resources/ have the source code of the diagrams, as well as the images used on the readme.

2023-08-03 21:42 UTC, brschettini requested changes
It was really difficult to review the code since I did not see the whole code in a first version PR.

Although you did a good job on reaching the task requirements.

Since you reached the task objective using functional programming, I will show you how we can do it by using OOP, which is more suitable for unit testing.

Good job.

2023-08-03 21:42 UTC, brschettini commented on README.md
> +This repository was developed to accomplish the proposed challenge of to get a transformed point B obtained from the point PA = [aPx aPy aPz] after applying a translation of [ 1 2 3 ] and a rotation
```suggestion
This repository was developed to accomplish the proposed challenge of to get a transformed point B obtained from the point PA = [aPx aPy aPz] after applying a translation of [ 1 2 3 ] and a rotation around x axis of theta degrees. Also, it was required to document the solution through a Use Case Diagram and a Sequence Diagram.
```

2023-08-03 21:42 UTC, brschettini commented on README.md
> +float64[3] point_a
It could be a "point" for both request and response interfaces since they differ by the context.

2023-08-03 21:42 UTC, brschettini commented on README.md
> +float64[3] point_a
Also I would exepect the reusability of common interfaces, like https://github.com/ros2/common_interfaces/blob/rolling/geometry_msgs/msg/Point.msg

2023-08-03 21:42 UTC, brschettini commented on README.md
> +float64[3] point_b
Same applies here.

2023-08-03 21:42 UTC, brschettini commented on README.md
> +The sequence diagram of the solution is presented bellow. Through this diagram it is possible to see how the information flow between the user, the client and the server, as well as the logic executi
```suggestion
The sequence diagram of the solution is presented bellow. Firstly, the user send a point and a rotation angle (around x-axis) to the client. This prepare the SRV message and send the information forward to the server. This one make the mathematical operations to calculate the desired point B, which is send back to the client as a response and, finally, achieve the user.
```

2023-08-03 21:42 UTC, brschettini commented on resources/diagrams_uml/use_case.plantuml
> +rectangle Service {
Put the name of the node/application instead of "Service"

2023-08-03 21:42 UTC, brschettini commented on src/get_transform_client.cpp
It is really strange since your first version is not fully included in the Pull Request. Make sure that this not happen in future peer review.

2023-08-03 21:42 UTC, brschettini commented on src/get_transform_client.cpp
> +    return 1;
Too much information. The original one was ok for me. It is simple and direct. If the number of arguments is not 5, then the system reports the correct usage of the application and return ends the main function.

2023-08-03 21:42 UTC, brschettini commented on src/get_transform_client.cpp
> +    RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Error: Invalid argument. The string does not represent a valid number");
Which string?

2023-08-03 21:42 UTC, brschettini commented on src/get_transform_client.cpp
> +    return 2;
Usually for errors we return -1

2023-08-03 21:42 UTC, brschettini commented on src/get_transform_client.cpp
>      if (!rclcpp::ok()) {
return 0 for error?

Careful.

2023-08-03 21:42 UTC, brschettini commented on src/get_transform_client.cpp
>    }
Line 50 is not consistent on your code style.

2023-08-03 21:42 UTC, brschettini commented on src/get_transform_server.cpp
> +# define M_PI 3.14159265358979323846  // pi approximation
```suggestion
# define M_PI 3.14159265358979323846  // pi
```

2023-08-03 21:42 UTC, brschettini commented on src/get_transform_server.cpp
>  {
```suggestion
void transform(const std::shared_ptr<apply_transform::srv::GetTransform::Request> request,
          std::shared_ptr<apply_transform::srv::GetTransform::Response>     response) {
```

2023-08-03 21:42 UTC, brschettini commented on src/get_transform_server.cpp
> +  double theta_rad = (request->theta)*M_PI/180; // convert from degrees to rad
Why not creating a function for it?

2023-08-03 21:42 UTC, brschettini commented on src/get_transform_server.cpp
>    RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "sending back response");
Explicitely return the function

2023-08-04 17:11 UTC, gabrielcalmon commented on src/get_transform_client.cpp
I didn't understand very well. What exactly is the problem here?

2023-08-04 17:31 UTC, gabrielcalmon commented
The sugestions and requests were implemented.

2023-08-10 17:15 UTC, merged